#!/bin/sh

cat <<EOF
Welcome to the restricted login shell for Git!
Run 'help' for help, or 'exit' to leave.  Available commands:
-------------------------------------------------------------
EOF

cd "$(dirname "$0")" || exit 1

for cmd in *
do
	case "$cmd" in
	help) ;;
	*) [ -f "$cmd" ] && [ -x "$cmd" ] && echo "$cmd" ;;
	esac
done

printf '\n'
